FROM ros:humble-ros-base-jammy
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions python3-opencv python3-serial python3-pytest \
    ros-humble-cv-bridge ros-humble-tf2-ros ros-humble-tf2-geometry-msgs \
    ros-humble-diagnostic-msgs git && rm -rf /var/lib/apt/lists/*
ARG PX4_MSGS_REF=a1045ec4feb6d709bdecaf3895f1d5b43a5dabb8
RUN git init /deps/src/px4_msgs && \
    git -C /deps/src/px4_msgs remote add origin https://github.com/PX4/px4_msgs.git && \
    git -C /deps/src/px4_msgs fetch --depth 1 origin ${PX4_MSGS_REF} && \
    git -C /deps/src/px4_msgs checkout --detach FETCH_HEAD
RUN . /opt/ros/humble/setup.sh && cd /deps && colcon build --executor sequential
WORKDIR /workspace
